name: 💡 Feature Request
description: Suggest a new feature or enhancement for crush-flake
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible about your idea.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-flight checklist
      description: Please verify these items before submitting your feature request
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested yet
          required: true
        - label: This feature request is related to the flake packaging, not the upstream Crush application
          required: true
        - label: I have considered if this could be implemented as a third-party extension or tool
          required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: Describe the problem or limitation you're experiencing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution in detail
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or workarounds have you considered?
      placeholder: Describe any alternative approaches you've thought about
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide concrete examples of how this feature would be used
      placeholder: |
        ```bash
        # Example command or usage
        nix run github:conneroisu/crush-flake -- new-feature --option
        ```
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking current work)
        - High (significantly improves workflow)
        - Medium (nice to have improvement)
        - Low (minor convenience)
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to implement this feature myself
        - label: I can help with testing and feedback
        - label: I can help with documentation
        - label: I need someone else to implement this

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or information about the feature request
    validations:
      required: false